# Generated by Django 4.1.7 on 2023-11-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('O', 'Other'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('password', models.TextField()),
                ('status', models.CharField(choices=[('R', 'Regular'), ('P', 'Premium'), ('G', 'Gold'), ('D', 'Diamond')], default='R', max_length=5)),
                ('avatar', models.ImageField(blank=True, upload_to='client/avatar')),
                ('joined', models.DateField(auto_now=True)),
            ],
        ),
    ]
